# Generated by Django 5.0.6 on 2024-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_creator", "0006_referenceblogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="language",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="referenceblogpost",
            name="keywords",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="referenceblogpost",
            name="language",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="referenceblogpost",
            name="length",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
