# Generated by Django 5.0.6 on 2024-09-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_creator",
            "0007_blogpost_language_referenceblogpost_keywords_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
