# Generated by Django 5.0.6 on 2024-09-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_creator", "0008_blogpost_meta_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="meta_description",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
