# Generated by Django 5.0.6 on 2024-09-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_creator", "0009_alter_blogpost_meta_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="length",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="reference",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
